spring:
  profiles:
    include:
    - db
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/inventory_management_system
    username: username
    password: "password"